-- BOTICA BIOENERGÉTICA
-- Execute este arquivo inteiro no SQL Editor do Supabase.

create table if not exists public.produtos (
  id bigint generated by default as identity primary key,
  nome text not null,
  descricao text not null,
  categoria text not null,
  preco numeric(10,2) not null check (preco >= 0),
  preco_antigo numeric(10,2),
  estoque integer not null default 0 check (estoque >= 0),
  imagem_url text,
  ativo boolean not null default true,
  criado_em timestamptz not null default now()
);

create table if not exists public.perfis (
  id uuid primary key references auth.users(id) on delete cascade,
  nome text,
  telefone text,
  funcao text not null default 'cliente' check (funcao in ('cliente','admin')),
  criado_em timestamptz not null default now()
);

create table if not exists public.enderecos (
  id bigint generated by default as identity primary key,
  usuario_id uuid not null references auth.users(id) on delete cascade,
  cep text not null,
  rua text not null,
  numero text not null,
  complemento text,
  bairro text not null,
  cidade text not null,
  estado text not null,
  criado_em timestamptz not null default now()
);

create table if not exists public.pedidos (
  id bigint generated by default as identity primary key,
  usuario_id uuid not null references auth.users(id),
  endereco_id bigint references public.enderecos(id),
  status text not null default 'aguardando_pagamento' check (status in ('aguardando_pagamento','pago','em_preparo','enviado','entregue','cancelado')),
  total numeric(10,2) not null check (total >= 0),
  frete numeric(10,2) not null default 0,
  codigo_rastreio text,
  criado_em timestamptz not null default now()
);

create table if not exists public.itens_pedido (
  id bigint generated by default as identity primary key,
  pedido_id bigint not null references public.pedidos(id) on delete cascade,
  produto_id bigint not null references public.produtos(id),
  quantidade integer not null check (quantidade > 0),
  preco_unitario numeric(10,2) not null check (preco_unitario >= 0)
);

alter table public.pedidos add column if not exists mercado_pago_preference_id text;
alter table public.pedidos add column if not exists pagamento_id text;
alter table public.pedidos add column if not exists pago_em timestamptz;
create unique index if not exists pedidos_pagamento_id_unico on public.pedidos(pagamento_id) where pagamento_id is not null;

create or replace function public.confirmar_pagamento(p_pedido_id bigint, p_pagamento_id text, p_valor numeric)
returns boolean language plpgsql security definer set search_path = public as $$
declare v_pedido public.pedidos%rowtype; v_item record;
begin
  select * into v_pedido from public.pedidos where id = p_pedido_id for update;
  if not found then raise exception 'Pedido não encontrado'; end if;
  if v_pedido.status = 'pago' then return true; end if;
  if round(v_pedido.total, 2) <> round(p_valor, 2) then raise exception 'Valor divergente'; end if;
  for v_item in select produto_id, quantidade from public.itens_pedido where pedido_id = p_pedido_id loop
    update public.produtos set estoque = estoque - v_item.quantidade where id = v_item.produto_id and estoque >= v_item.quantidade;
    if not found then raise exception 'Estoque insuficiente'; end if;
  end loop;
  update public.pedidos set status = 'pago', pagamento_id = p_pagamento_id, pago_em = now() where id = p_pedido_id;
  return true;
end;
$$;
revoke all on function public.confirmar_pagamento(bigint, text, numeric) from public, anon, authenticated;
grant execute on function public.confirmar_pagamento(bigint, text, numeric) to service_role;

create table if not exists public.receitas (
  id bigint generated by default as identity primary key,
  usuario_id uuid not null references auth.users(id) on delete cascade,
  arquivo_url text not null,
  observacao text,
  status text not null default 'em_analise' check (status in ('em_analise','orcamento_enviado','aprovada','recusada')),
  criado_em timestamptz not null default now()
);

create or replace function public.criar_perfil_novo_usuario()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.perfis (id, nome)
  values (new.id, new.raw_user_meta_data ->> 'nome')
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists ao_criar_usuario on auth.users;
create trigger ao_criar_usuario after insert on auth.users
for each row execute procedure public.criar_perfil_novo_usuario();

create or replace function public.usuario_e_admin()
returns boolean language sql stable security definer set search_path = public as $$
  select exists(select 1 from public.perfis where id = auth.uid() and funcao = 'admin');
$$;

alter table public.produtos enable row level security;
alter table public.perfis enable row level security;
alter table public.enderecos enable row level security;
alter table public.pedidos enable row level security;
alter table public.itens_pedido enable row level security;
alter table public.receitas enable row level security;

drop policy if exists "Produtos ativos são públicos" on public.produtos;
create policy "Produtos ativos são públicos" on public.produtos for select using (ativo = true or public.usuario_e_admin());
drop policy if exists "Admin gerencia produtos" on public.produtos;
create policy "Admin gerencia produtos" on public.produtos for all using (public.usuario_e_admin()) with check (public.usuario_e_admin());

drop policy if exists "Usuário vê próprio perfil" on public.perfis;
create policy "Usuário vê próprio perfil" on public.perfis for select using (id = auth.uid() or public.usuario_e_admin());
drop policy if exists "Usuário atualiza próprio perfil" on public.perfis;
create policy "Usuário atualiza próprio perfil" on public.perfis for update using (id = auth.uid()) with check (id = auth.uid());

drop policy if exists "Usuário gerencia endereços" on public.enderecos;
create policy "Usuário gerencia endereços" on public.enderecos for all using (usuario_id = auth.uid() or public.usuario_e_admin()) with check (usuario_id = auth.uid() or public.usuario_e_admin());

drop policy if exists "Usuário vê pedidos" on public.pedidos;
create policy "Usuário vê pedidos" on public.pedidos for select using (usuario_id = auth.uid() or public.usuario_e_admin());
drop policy if exists "Usuário cria pedido" on public.pedidos;
create policy "Usuário cria pedido" on public.pedidos for insert with check (usuario_id = auth.uid());
drop policy if exists "Admin atualiza pedidos" on public.pedidos;
create policy "Admin atualiza pedidos" on public.pedidos for update using (public.usuario_e_admin());

drop policy if exists "Usuário vê itens dos pedidos" on public.itens_pedido;
create policy "Usuário vê itens dos pedidos" on public.itens_pedido for select using (
  exists(select 1 from public.pedidos p where p.id = pedido_id and (p.usuario_id = auth.uid() or public.usuario_e_admin()))
);
drop policy if exists "Usuário adiciona itens ao pedido" on public.itens_pedido;
create policy "Usuário adiciona itens ao pedido" on public.itens_pedido for insert with check (
  exists(select 1 from public.pedidos p where p.id = pedido_id and p.usuario_id = auth.uid())
);

drop policy if exists "Usuário gerencia receitas" on public.receitas;
create policy "Usuário gerencia receitas" on public.receitas for all using (usuario_id = auth.uid() or public.usuario_e_admin()) with check (usuario_id = auth.uid() or public.usuario_e_admin());

-- Depois de criar sua conta no site, troque o e-mail abaixo e execute apenas esta linha:
-- update public.perfis set funcao = 'admin' where id = (select id from auth.users where email = 'SEU_EMAIL@EXEMPLO.COM');
