-- Execute este arquivo uma vez no SQL Editor do Supabase.
-- Ele cria somente a estrutura necessária para endereços e pedidos.

create table if not exists public.enderecos (
  id bigint generated by default as identity primary key,
  usuario_id uuid not null references auth.users(id) on delete cascade,
  cep text not null, rua text not null, numero text not null, complemento text,
  bairro text not null, cidade text not null, estado text not null,
  criado_em timestamptz not null default now()
);

create table if not exists public.pedidos (
  id bigint generated by default as identity primary key,
  usuario_id uuid not null references auth.users(id) on delete cascade,
  endereco_id bigint references public.enderecos(id),
  status text not null default 'aguardando_pagamento',
  total numeric(10,2) not null check (total >= 0),
  frete numeric(10,2) not null default 0,
  codigo_rastreio text,
  criado_em timestamptz not null default now()
);

create table if not exists public.itens_pedido (
  id bigint generated by default as identity primary key,
  pedido_id bigint not null references public.pedidos(id) on delete cascade,
  produto_id bigint not null references public.produtos(id),
  quantidade integer not null check (quantidade > 0),
  preco_unitario numeric(10,2) not null check (preco_unitario >= 0)
);

alter table public.pedidos add column if not exists mercado_pago_preference_id text;
alter table public.pedidos add column if not exists pagamento_id text;
alter table public.pedidos add column if not exists pago_em timestamptz;
create unique index if not exists pedidos_pagamento_id_unico on public.pedidos(pagamento_id) where pagamento_id is not null;

create or replace function public.confirmar_pagamento(p_pedido_id bigint, p_pagamento_id text, p_valor numeric)
returns boolean language plpgsql security definer set search_path = public as $$
declare v_pedido public.pedidos%rowtype; v_item record;
begin
  select * into v_pedido from public.pedidos where id = p_pedido_id for update;
  if not found then raise exception 'Pedido não encontrado'; end if;
  if v_pedido.status = 'pago' then return true; end if;
  if round(v_pedido.total, 2) <> round(p_valor, 2) then raise exception 'Valor divergente'; end if;
  for v_item in select produto_id, quantidade from public.itens_pedido where pedido_id = p_pedido_id loop
    update public.produtos set estoque = estoque - v_item.quantidade where id = v_item.produto_id and estoque >= v_item.quantidade;
    if not found then raise exception 'Estoque insuficiente'; end if;
  end loop;
  update public.pedidos set status = 'pago', pagamento_id = p_pagamento_id, pago_em = now() where id = p_pedido_id;
  return true;
end;
$$;
revoke all on function public.confirmar_pagamento(bigint, text, numeric) from public, anon, authenticated;
grant execute on function public.confirmar_pagamento(bigint, text, numeric) to service_role;

alter table public.enderecos enable row level security;
alter table public.pedidos enable row level security;
alter table public.itens_pedido enable row level security;

drop policy if exists "Usuário gerencia endereços" on public.enderecos;
create policy "Usuário gerencia endereços" on public.enderecos for all
using (usuario_id = auth.uid()) with check (usuario_id = auth.uid());

drop policy if exists "Usuário vê pedidos" on public.pedidos;
create policy "Usuário vê pedidos" on public.pedidos for select using (usuario_id = auth.uid());
drop policy if exists "Usuário cria pedido" on public.pedidos;
create policy "Usuário cria pedido" on public.pedidos for insert with check (usuario_id = auth.uid());

drop policy if exists "Usuário vê itens dos pedidos" on public.itens_pedido;
create policy "Usuário vê itens dos pedidos" on public.itens_pedido for select using (
  exists(select 1 from public.pedidos p where p.id = pedido_id and p.usuario_id = auth.uid())
);
drop policy if exists "Usuário adiciona itens ao pedido" on public.itens_pedido;
create policy "Usuário adiciona itens ao pedido" on public.itens_pedido for insert with check (
  exists(select 1 from public.pedidos p where p.id = pedido_id and p.usuario_id = auth.uid())
);
