-- LGPD e proteção contra abuso. Execute no SQL Editor do Supabase.
-- É seguro executar novamente.

alter table public.newsletter_inscritos
  add column if not exists consentimento_em timestamptz,
  add column if not exists politica_versao text,
  add column if not exists origem text,
  add column if not exists cancelado_em timestamptz;

create table if not exists public.solicitacoes_lgpd (
  id bigint generated by default as identity primary key,
  usuario_id uuid not null references auth.users(id) on delete cascade,
  tipo text not null check (tipo in ('acesso','correcao','eliminacao','portabilidade','revogacao','oposicao','outro')),
  detalhes text not null check (char_length(detalhes) between 10 and 2000),
  status text not null default 'recebida' check (status in ('recebida','em_analise','concluida','recusada')),
  resposta_admin text,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create index if not exists solicitacoes_lgpd_usuario_idx on public.solicitacoes_lgpd(usuario_id, criado_em desc);
alter table public.solicitacoes_lgpd enable row level security;
drop policy if exists "Titular visualiza solicitações LGPD" on public.solicitacoes_lgpd;
create policy "Titular visualiza solicitações LGPD" on public.solicitacoes_lgpd for select using (usuario_id = auth.uid() or public.usuario_e_admin());
drop policy if exists "Titular cria solicitação LGPD" on public.solicitacoes_lgpd;
create policy "Titular cria solicitação LGPD" on public.solicitacoes_lgpd for insert with check (usuario_id = auth.uid());
drop policy if exists "Admin atualiza solicitações LGPD" on public.solicitacoes_lgpd;
create policy "Admin atualiza solicitações LGPD" on public.solicitacoes_lgpd for update using (public.usuario_e_admin());

create table if not exists public.api_rate_limits (
  chave text not null,
  janela_inicio timestamptz not null,
  quantidade integer not null default 1,
  primary key (chave, janela_inicio)
);
alter table public.api_rate_limits enable row level security;
revoke all on table public.api_rate_limits from public, anon, authenticated;

create or replace function public.consumir_limite_api(p_chave text, p_limite integer, p_janela_segundos integer)
returns boolean language plpgsql security definer set search_path = public as $$
declare v_inicio timestamptz; v_quantidade integer;
begin
  if p_limite < 1 or p_janela_segundos < 1 then return false; end if;
  v_inicio := to_timestamp(floor(extract(epoch from now()) / p_janela_segundos) * p_janela_segundos);
  insert into public.api_rate_limits(chave, janela_inicio, quantidade) values (p_chave, v_inicio, 1)
  on conflict (chave, janela_inicio) do update set quantidade = public.api_rate_limits.quantidade + 1
  returning quantidade into v_quantidade;
  if random() < 0.02 then delete from public.api_rate_limits where janela_inicio < now() - interval '2 days'; end if;
  return v_quantidade <= p_limite;
end;
$$;
revoke all on function public.consumir_limite_api(text, integer, integer) from public, anon, authenticated;
grant execute on function public.consumir_limite_api(text, integer, integer) to service_role;
