-- Execute este arquivo uma vez no SQL Editor do Supabase.
-- É seguro executar novamente.
create table if not exists public.newsletter_inscritos (
  id bigint generated by default as identity primary key,
  email text not null,
  ativo boolean not null default true,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create unique index if not exists newsletter_inscritos_email_unico
  on public.newsletter_inscritos (email);

alter table public.newsletter_inscritos enable row level security;

-- O cadastro é feito apenas pela rota protegida do servidor usando a service role.
revoke all on table public.newsletter_inscritos from anon, authenticated;
