-- Execute este arquivo no SQL Editor do Supabase.
-- É seguro executar novamente.

alter table public.pedidos
  add column if not exists transportadora text,
  add column if not exists codigo_rastreio text,
  add column if not exists link_rastreio text,
  add column if not exists status_entrega text not null default 'preparando',
  add column if not exists rastreio_atualizado_em timestamptz,
  add column if not exists entregue_em timestamptz;

create table if not exists public.solicitacoes_pos_venda (
  id bigint generated by default as identity primary key,
  pedido_id bigint not null references public.pedidos(id) on delete cascade,
  usuario_id uuid not null references auth.users(id) on delete cascade,
  tipo text not null check (tipo in ('arrependimento', 'troca', 'devolucao', 'defeito', 'reembolso')),
  motivo text not null,
  detalhes text,
  status text not null default 'em_analise' check (status in ('em_analise', 'aprovada', 'recusada', 'aguardando_envio', 'produto_recebido', 'reembolso_processado', 'concluida')),
  resposta_admin text,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create index if not exists solicitacoes_pos_venda_usuario_idx
  on public.solicitacoes_pos_venda(usuario_id, criado_em desc);

alter table public.solicitacoes_pos_venda enable row level security;

drop policy if exists "Cliente visualiza solicitações próprias" on public.solicitacoes_pos_venda;
create policy "Cliente visualiza solicitações próprias" on public.solicitacoes_pos_venda
  for select using (usuario_id = auth.uid());

drop policy if exists "Cliente cria solicitação própria" on public.solicitacoes_pos_venda;
create policy "Cliente cria solicitação própria" on public.solicitacoes_pos_venda
  for insert with check (
    usuario_id = auth.uid()
    and exists (
      select 1 from public.pedidos p
      where p.id = pedido_id and p.usuario_id = auth.uid()
    )
  );
