-- Execute este arquivo uma vez no SQL Editor do Supabase.
create table if not exists public.receitas (
  id bigint generated by default as identity primary key,
  usuario_id uuid not null references auth.users(id) on delete cascade,
  arquivo_url text not null,
  observacao text,
  resposta_admin text,
  status text not null default 'em_analise'
    check (status in ('em_analise','orcamento_enviado','aprovada','recusada')),
  criado_em timestamptz not null default now()
);

alter table public.receitas
  add column if not exists resposta_admin text;

alter table public.receitas enable row level security;

drop policy if exists "Usuário gerencia receitas" on public.receitas;
create policy "Usuário gerencia receitas"
on public.receitas for all
using (usuario_id = auth.uid())
with check (usuario_id = auth.uid());

-- O painel administrativo acessa as receitas pelo servidor usando a
-- service_role do Supabase, que ignora o RLS com segurança. Por isso esta
-- instalação não depende da função usuario_e_admin() do banco completo.

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'receitas-privadas',
  'receitas-privadas',
  false,
  10485760,
  array['application/pdf','image/jpeg','image/png']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;
