"use client";

import { FormEvent, useState } from "react";

type Receita = { id: number; status: string; observacao?: string | null; resposta_admin?: string | null; criado_em: string; cliente?: { nome?: string | null; email?: string | null } };

export function AdminRecipes({ receitas, erroConfiguracao }: { receitas: Receita[]; erroConfiguracao?: string }) {
  const [mensagem, setMensagem] = useState(""); const [salvando, setSalvando] = useState<number | null>(null);
  async function abrir(id: number) { const resposta = await fetch(`/api/admin/receitas/${id}`); const dados = await resposta.json(); if (dados.url) window.open(dados.url, "_blank", "noopener,noreferrer"); else setMensagem(dados.erro); }
  async function atualizar(evento: FormEvent<HTMLFormElement>, id: number) { evento.preventDefault(); setSalvando(id); const form = new FormData(evento.currentTarget); const resposta = await fetch(`/api/admin/receitas/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status: form.get("status"), mensagem: form.get("mensagem") }) }); const dados = await resposta.json(); setMensagem(dados.mensagem || dados.erro); setSalvando(null); if (resposta.ok && dados.enviado) setTimeout(() => location.reload(), 900); }
  return <section className="admin-recipes"><div className="admin-panel-heading"><div><small>MANIPULAÇÃO</small><h2>Receitas recebidas</h2><p>Visualize os arquivos enviados, escreva a resposta e avise o cliente por e-mail.</p></div><span>{receitas.length} RECEITAS</span></div>{mensagem && <p className="admin-toast">{mensagem}</p>}{erroConfiguracao && <p className="admin-recipe-warning">{erroConfiguracao}</p>}<div className="admin-recipe-list">{receitas.length ? receitas.map((receita) => <article key={receita.id}><header><div><small>RECEITA</small><h3>Solicitação #{receita.id}</h3></div><span>{receita.status.replaceAll("_", " ")}</span></header><div className="admin-recipe-customer"><small>CLIENTE</small><b>{receita.cliente?.nome || "Nome não informado"}</b><span>{receita.cliente?.email || "E-mail não encontrado"}</span><em>{new Date(receita.criado_em).toLocaleDateString("pt-BR")}</em></div>{receita.observacao && <p>{receita.observacao}</p>}<form className="admin-recipe-response" onSubmit={(evento) => atualizar(evento, receita.id)}><label>Status da receita<select name="status" defaultValue={receita.status} disabled={salvando === receita.id}><option value="em_analise">Em análise</option><option value="orcamento_enviado">Orçamento enviado</option><option value="aprovada">Aprovada</option><option value="recusada">Recusada</option></select></label><label>Mensagem para o cliente<textarea name="mensagem" defaultValue={receita.resposta_admin || ""} placeholder="Ex.: Analisamos sua receita. O orçamento está pronto e entraremos em contato..." required /></label><div className="admin-recipe-actions"><button type="button" onClick={() => abrir(receita.id)}>ABRIR ARQUIVO</button><button type="submit" disabled={salvando === receita.id}>{salvando === receita.id ? "ENVIANDO..." : "SALVAR E AVISAR CLIENTE"}</button></div></form></article>) : <div className="admin-none">{erroConfiguracao ? "Recebimento aguardando configuração." : "Nenhuma receita recebida."}</div>}</div></section>;
}
