"use client";

import { useState } from "react";

type Receita = { id: number; status: string; observacao?: string | null; criado_em: string; cliente?: { nome?: string | null; email?: string | null } };

export function AdminRecipes({ receitas, erroConfiguracao }: { receitas: Receita[]; erroConfiguracao?: string }) {
  const [mensagem, setMensagem] = useState(""); const [salvando, setSalvando] = useState<number | null>(null);
  async function abrir(id: number) { const resposta = await fetch(`/api/admin/receitas/${id}`); const dados = await resposta.json(); if (dados.url) window.open(dados.url, "_blank", "noopener,noreferrer"); else setMensagem(dados.erro); }
  async function atualizar(id: number, status: string) { setSalvando(id); const resposta = await fetch(`/api/admin/receitas/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status }) }); const dados = await resposta.json(); setMensagem(dados.mensagem || dados.erro); setSalvando(null); if (resposta.ok) setTimeout(() => location.reload(), 700); }
  return <section className="admin-recipes"><div className="admin-panel-heading"><div><small>MANIPULAÇÃO</small><h2>Receitas recebidas</h2><p>Visualize os arquivos enviados, acompanhe a análise e avise o cliente.</p></div><span>{receitas.length} RECEITAS</span></div>{mensagem && <p className="admin-toast">{mensagem}</p>}{erroConfiguracao && <p className="admin-recipe-warning">{erroConfiguracao}</p>}<div className="admin-recipe-list">{receitas.length ? receitas.map((receita) => <article key={receita.id}><header><div><small>RECEITA</small><h3>Solicitação #{receita.id}</h3></div><span>{receita.status.replaceAll("_", " ")}</span></header><div className="admin-recipe-customer"><small>CLIENTE</small><b>{receita.cliente?.nome || "Nome não informado"}</b><span>{receita.cliente?.email || "E-mail não encontrado"}</span><em>{new Date(receita.criado_em).toLocaleDateString("pt-BR")}</em></div>{receita.observacao && <p>{receita.observacao}</p>}<div className="admin-recipe-actions"><button onClick={() => abrir(receita.id)}>ABRIR ARQUIVO</button><select defaultValue={receita.status} disabled={salvando === receita.id} onChange={(e) => atualizar(receita.id, e.target.value)}><option value="em_analise">Em análise</option><option value="orcamento_enviado">Orçamento enviado</option><option value="aprovada">Aprovada</option><option value="recusada">Recusada</option></select></div></article>) : <div className="admin-none">{erroConfiguracao ? "Recebimento aguardando configuração." : "Nenhuma receita recebida."}</div>}</div></section>;
}
