export default function PoliticaPrivacidadePage() {
  return <main className="policy-page"><header className="policy-hero"><div><small>LGPD • VERSÃO 17/09/2026</small><h1>Política de Privacidade e Cookies</h1></div><p>Informações claras sobre como a Botica Bioenergética utiliza e protege seus dados pessoais.</p></header><div className="policy-layout"><aside><b>Nesta página</b><a href="#controlador">Controlador</a><a href="#dados">Dados tratados</a><a href="#finalidades">Finalidades</a><a href="#compartilhamento">Compartilhamento</a><a href="#cookies">Cookies</a><a href="#seguranca">Segurança</a><a href="#direitos">Seus direitos</a></aside><article>
    <section id="controlador"><span>01</span><div><h2>Controlador e contato</h2><p>A Botica Bioenergética, CNPJ 13.013.360/0001-70, com endereço na Rua Sol da Meia-Noite, 990, Jardim Maia, São Paulo/SP, CEP 08180-050, é responsável pelas decisões sobre o tratamento realizado neste site.</p><p>O canal para assuntos de privacidade, exercício de direitos e comunicação de incidentes é <a href="mailto:raphad2712@gmail.com?subject=Privacidade%20e%20LGPD">raphad2712@gmail.com</a>. Também disponibilizamos a <a href="/privacidade">Central de Privacidade</a>.</p></div></section>
    <section id="dados"><span>02</span><div><h2>Dados pessoais tratados</h2><p>Podemos tratar dados de cadastro e contato; CPF; data de nascimento e gênero quando informados; endereço; pedidos, pagamentos e entregas; comunicações de atendimento; preferências de cookies; registros técnicos de segurança; e-mail de newsletter e prova do consentimento.</p><p>Prescrições, fórmulas e informações fornecidas para manipulação podem revelar dados de saúde e recebem proteção reforçada como dados pessoais sensíveis. Não informe dados que não sejam necessários ao atendimento farmacêutico.</p></div></section>
    <section id="finalidades"><span>03</span><div><h2>Finalidades e bases legais</h2><p>Os dados são utilizados para criar e proteger a conta, processar compras e pagamentos, entregar pedidos, atender solicitações, analisar prescrições, prevenir fraude, cumprir obrigações legais e regulatórias e exercer direitos em processos. Comunicações promocionais são realizadas com consentimento, que pode ser retirado gratuitamente.</p><p>Quando o fornecimento for indispensável para uma compra, receita ou obrigação legal, isso será indicado no formulário correspondente.</p></div></section>
    <section id="compartilhamento"><span>04</span><div><h2>Operadores e compartilhamento</h2><p>Dados estritamente necessários podem ser compartilhados com provedores de hospedagem e banco de dados, processamento de pagamentos, e-mail, frete e transportadoras, contabilidade e autoridades competentes. Atualmente, o site integra serviços como Supabase, Vercel, PagBank, Brevo e Melhor Envio. Cada fornecedor recebe somente os dados necessários à sua função.</p><p>Alguns fornecedores podem armazenar ou processar dados fora do Brasil. Nesses casos, a Botica deve adotar salvaguardas e mecanismos admitidos pela LGPD.</p></div></section>
    <section id="cookies"><span>05</span><div><h2>Cookies e armazenamento local</h2><p>Cookies necessários mantêm autenticação e segurança. O armazenamento local do navegador guarda carrinho, favoritos, tema, CEP e a escolha de privacidade. Eles são essenciais ou funcionais e não são usados para publicidade comportamental.</p><p>Cookies opcionais de análise ou publicidade somente poderão ser ativados após autorização específica. Recusar opcionais não impede as funções essenciais. A preferência pode ser alterada no rodapé.</p></div></section>
    <section id="seguranca"><span>06</span><div><h2>Segurança e conservação</h2><p>São aplicadas medidas técnicas e administrativas como conexão HTTPS, controle de acesso, políticas de banco de dados, validação de arquivos, limitação de tentativas e armazenamento privado de prescrições. Nenhum sistema é infalível; suspeitas de incidente devem ser comunicadas imediatamente pelo canal de privacidade.</p><p>Os dados são mantidos somente pelo tempo necessário às finalidades informadas e aos prazos legais, fiscais, sanitários e de defesa de direitos. Após esse período, são eliminados ou anonimizados quando possível.</p></div></section>
    <section id="direitos"><span>07</span><div><h2>Direitos do titular</h2><p>Você pode solicitar confirmação do tratamento, acesso, correção, anonimização, bloqueio ou eliminação de dados desnecessários, portabilidade quando regulamentada, informação sobre compartilhamentos, revisão de decisões automatizadas, oposição e revogação do consentimento. Obrigações legais podem impedir a exclusão imediata de determinados registros.</p><p>Use a <a href="/privacidade">Central de Privacidade</a>. Poderemos solicitar comprovação de identidade antes de entregar ou alterar dados. Se não houver solução, você também pode peticionar perante a Autoridade Nacional de Proteção de Dados.</p></div></section>
    <section id="menores"><span>08</span><div><h2>Crianças, atualizações e legislação</h2><p>O site não é direcionado a crianças. Dados de menores somente devem ser enviados por responsável legal e quando necessários ao atendimento, observando o melhor interesse do titular.</p><p>Esta política poderá ser atualizada para refletir mudanças legais ou operacionais. Alterações relevantes serão destacadas. O tratamento observa a Lei nº 13.709/2018 — Lei Geral de Proteção de Dados Pessoais.</p></div></section>
  </article></div></main>;
}
